const ShopData = [
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHbnGXMUfBlrIlVVsMHHLyvXWwpxwhptBfIQ&usqp=CAU",
    name: "Moti Mahal",
    add: "Bistupur",
    rating: 4,
    id: 1,
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS523rDJVpPhDTpg8nUmLlm1H2c3Tya6jjQxQ&usqp=CAU",
    name: "Blue Diamond",
    add: "Sakchi",
    rating: 3,
    id: 1,
  },
  {
    img: "https://assets.telegraphindia.com/telegraph/25b05c47-ba50-44be-b911-deade94fbe0d.jpg",
    name: "The Alcor",
    add: "Bistupur",
    rating: 5,
    id: 1,
  },
  {
    img: "https://i.ytimg.com/vi/fo8ZhVK0Kg0/mqdefault.jpg",
    name: "Oxygen",
    add: "Bistupur",
    rating: 3,
    id: 1,
  },
  {
    img: "https://gos3.ibcdn.com/de52feb8c96d11edafd40a58a9feac02.jpg",
    name: "The Cruze",
    add: "Bistupur",
    rating: 4,
    id: 1,
  },
  {img:"https://5bestincity.com/listimg/India/jamshedpur-jh/Dalchini-Family-Restaurant-Food-Family-restaurants-Jamshedpur-Jharkhand.jpg",
    name: "The Dalchini",
    add: "Bistupur",
    rating: 4,
    id: 1,
  },
  {
    img: "https://i.ytimg.com/vi/_Rt_wBvXkxU/sddefault.jpg",
    name: "Xero",
    add: "Bistupur",
    rating: 4,
    id: 1,
  },
  {
    img: "https://content3.jdmagicbox.com/comp/jamshedpur/u1/0657px657.x657.210911142526.l9u1/catalogue/banjara-restaurant-sonari-jamshedpur-restaurants-m0el1j2ukj.jpg",
    name: "Banjara",
    add: "Marindrive",
    rating: 3,
    id: 1,
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOx__pnzZE_mo3-tTZElJtcQtb-KXmUC4wTg&usqp=CAU",
    name: "Haveli ",
    add: "Sakchi",
    rating: 2,
    id: 1,
  },
    {
      img:"https://5bestincity.com/listimg/India/jamshedpur-jh/Novelty-Restaurant-Food-Family-restaurants-Jamshedpur-Jharkhand.jpg",
    name: "Novelty",
    add: "Adtiyapur",
    rating: 4,
    id: 1,
  },
];
export default ShopData;
